# Generated by Django 4.0 on 2022-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Title EN')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Title EN')),
                ('title_cz', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Title CZ')),
                ('content_en', models.TextField(blank=True, default=None, null=True, verbose_name='Content EN')),
                ('content_cz', models.TextField(blank=True, default=None, null=True, verbose_name='Content EN')),
                ('header_image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/', verbose_name='Header Image')),
                ('header_thumb', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Header Thumbnail')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
        ),
    ]
